version: '3.8'
services:
  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      # ローカルにバインドマウントしたくない場合
      # - /app/node_modules
      # ローカルにバインドマウントしたい場合
      - ./app/node_modules:/app/node_modules
      - ./app:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3030:3030'
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server:/app
    depends_on:
      - front

  npm:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./app:/app
      # ローカルにバインドマウントしたくない場合
      # - /app/node_modules
      # ローカルにバインドマウントしたい場合
      - ./app/node_modules:/app/node_modules

  # create-react-app
  create-react-app:
    image: node:16
    working_dir: /
    entrypoint: 'npx create-react-app app'
    volumes:
      - ./app:/app

  # First React App(Cypress)
  first-react:
    build:
      context: ./api-request
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    entrypoint: 'npm run start:frontend'
    volumes:
      - ./api-request:/app
      - ./api-request/node_modules:/app/node_modules
    depends_on:
      - first-server
  first-server:
    build:
      context: ./api-request
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    entrypoint: 'npm run start:server'
    volumes:
      - ./api-request/db.json:/app/db.json
      - ./api-request/routes.json:/app/routes.json
      - ./api-request/node_modules:/app/node_modules
