version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          working_directory: cypress-api-request
          command: npm run build:and:test

workflows:
  build:
    jobs:
      - test
      - cypress/run: # "run" job comes from "cypress" orb
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
