version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          command: npm run build:and:test
          working_directory: cypress-api-request
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "cypress-api-request/package.json" }}'
