pipeline{
  agent {
    docker {
      image 'cypress/base:16.13.0'
      // args '-u root:root -v /var/run/docker.sock:/var/run/docker.sock'
      alwaysPull false
      reuseNode true
    }
  }

  stages {
    stage('check logged in user') {
      steps {
        sh "whoami"
      }
    }
    stage('Download the dependencies') {
      steps {
        sh "npm install"
      }
    }

    stage('Build and test') {
      steps {
        sh "npm run build:and:test"
      }
    }
  }

}