pipeline {
    agent {
        docker {
          image 'cypress/base:16.13.0'
          args '-u root:root'
        }
      }
    stages {
        stage('Checkout') {
            steps {
              checkout([$class: 'GitSCM', 
                branches: [[name: 'jenkins/integration']],
                extensions: [
                    [$class: 'SparseCheckoutPaths', 
                    sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'/cypress-api-request']]]
                    ],
                userRemoteConfigs: [[url: 'https://github.com/ShotaroMatsuya/front-test-tools.git']]])
              sh "ls -ltr"
          }
        }
      stage('Download the dependencies') {
        steps {
          dir('cypress-api-request'){
            sh "npm install"
          }
        }
      }

      stage('Build and test') {
        steps {
          dir('cypress-api-request'){
            sh "npm run build:and:test"
          }
        }
      }
    }
}